In [3]:
%sql
USE CATALOG dev_flight_analytics;

DataFrame[]

In [4]:
%sql
CREATE SCHEMA IF NOT EXISTS dev_flight_analytics.bronze
COMMENT "Bronze schema for dev_flight_analytics catalog"
MANAGED LOCATION 's3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze';

DataFrame[]

In [5]:
%sql
CREATE SCHEMA IF NOT EXISTS dev_flight_analytics.silver
COMMENT "Silver schema for dev_flight_analytics catalog"
MANAGED LOCATION 's3://ragesh-databricks-s3-inputs/flight_analytics/dev/silver';

DataFrame[]

In [6]:
%sql
CREATE SCHEMA IF NOT EXISTS dev_flight_analytics.gold
COMMENT "Gold schema for dev_flight_analytics catalog"
MANAGED LOCATION 's3://ragesh-databricks-s3-inputs/flight_analytics/dev/gold';

DataFrame[]

In [25]:
%sql
DROP TABLE IF EXISTS dev_flight_analytics.bronze.flight_events; 
CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.flight_events (
    event_type STRING,
    flight_id STRING,
    flight_number STRING,
    old_status STRING,
    new_status STRING,
    delay_minutes INT,
    gate STRING,
    event_time TIMESTAMP,
    partition_key STRING,
    sequence_number LONG,
    offset LONG,
    message_id STRING,
    enqueued_time TIMESTAMP,
    created_time TIMESTAMP
)
USING DELTA
CLUSTER BY (event_type, flight_id)
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/flight_events";

DataFrame[]

In [26]:
%sql
DROP TABLE IF EXISTS dev_flight_analytics.bronze.booking_events;
CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.booking_events (
    event_type STRING,
    booking_id STRING,
    booking_flight_id STRING,
    flight_id STRING,
    passenger_id STRING,
    pnr STRING,
    old_status STRING,
    new_status STRING,
    event_time TIMESTAMP,
    partition_key STRING,
    sequence_number LONG,
    offset LONG,
    message_id STRING,
    enqueued_time TIMESTAMP,
    created_time TIMESTAMP
)
USING DELTA
CLUSTER BY (event_type, booking_id)
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/booking_events";

DataFrame[]

In [27]:
%sql
DROP TABLE IF EXISTS dev_flight_analytics.bronze.payment_events;
CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.payment_events (
    event_type STRING,
    payment_id STRING,
    booking_id STRING,
    payment_reference STRING,
    payment_method STRING,
    payment_amount DOUBLE,
    currency STRING,
    old_status STRING,
    new_status STRING,
    event_time TIMESTAMP,
    partition_key STRING,
    sequence_number LONG,
    offset LONG,
    message_id STRING,
    enqueued_time TIMESTAMP,
    created_time TIMESTAMP
)
USING DELTA
CLUSTER BY (event_type, payment_id)
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/payment_events";

DataFrame[]

In [1]:
%sql
DROP TABLE IF EXISTS dev_flight_analytics.bronze.booking_flight_events;

CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.booking_flight_events (
    booking_flight_id STRING,
    booking_id STRING,
    flight_id STRING,
    passenger_id STRING,
    seat_number STRING,
    cabin_class STRING,
    fare_class STRING,
    base_fare DOUBLE,
    taxes DOUBLE,
    total_fare DOUBLE,
    booking_status STRING,
    partition_key STRING,
    sequence_number LONG,
    offset LONG,
    message_id STRING,
    enqueued_time TIMESTAMP,
    created_time TIMESTAMP
)
USING DELTA
CLUSTER BY (booking_flight_id, booking_id)
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/booking_flight_events";

DataFrame[]

In [19]:
%sql
DROP TABLE IF EXISTS dev_flight_analytics.bronze.aircrafts;
CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.aircrafts (
    aircraft_id STRING,
    aircraft_model STRING,
    manufacturer STRING,
    total_seats INT,
    business_seats INT,
    economy_seats INT,
    first_class_seats INT,
    status STRING,
    created_time TIMESTAMP,
    updated_time TIMESTAMP
)
USING DELTA
CLUSTER BY (aircraft_id)
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/aircrafts";

DataFrame[]

In [20]:
%sql
DROP TABLE IF EXISTS dev_flight_analytics.bronze.airlines;

CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.airlines (
    flight_number STRING,
    airline_code STRING,
    airline_name STRING,
    origin_airport_code STRING,
    origin_airport_name STRING,
    destination_airport_code STRING,
    destination_airport_name STRING,
    departure_utc TIMESTAMP,
    arrival_utc TIMESTAMP,
    aircraft_model STRING,
    manufacturer STRING,
    aircraft_icao_code STRING,
    capacity INT,
    business_seats INT,
    economy_seats INT,
    first_class_seats INT,
    created_time TIMESTAMP,
    updated_time TIMESTAMP
)
USING DELTA
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/airlines";

DataFrame[]

In [21]:
%sql
DROP TABLE IF EXISTS dev_flight_analytics.bronze.airports;

CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.airports (
    airport_code STRING,
    city STRING,
    country_code STRING,
    country_name STRING,
    timezone STRING,
    created_time TIMESTAMP,
    updated_time TIMESTAMP
)
USING DELTA
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/airports";

DataFrame[]

In [22]:
%sql

DROP TABLE IF EXISTS dev_flight_analytics.bronze.flight_prices;
CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.flight_prices (
    flight_number STRING,
    airline_code STRING,
    origin_airport_code STRING,
    destination_airport_code STRING,
    departure_utc TIMESTAMP,
    arrival_utc TIMESTAMP,
    fare_class_code STRING,
    fare_class STRING,
    configured_seats INT,
    currency STRING,
    base_fare DOUBLE,
    tax_rate_percent DOUBLE,
    taxes DOUBLE,
    total_cost DOUBLE,
    created_time TIMESTAMP,
    updated_time TIMESTAMP
)
USING DELTA
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/flight_prices";

DataFrame[]

In [24]:
%sql
DROP TABLE IF EXISTS dev_flight_analytics.bronze.passengers;
CREATE EXTERNAL TABLE IF NOT EXISTS dev_flight_analytics.bronze.passengers (
    passenger_id STRING,
    first_name STRING,
    last_name STRING,
    date_of_birth DATE,
    gender STRING,
    email STRING,
    phone LONG,
    country STRING,
    loyalty_number STRING,
    created_time TIMESTAMP,
    updated_time TIMESTAMP
)
USING DELTA
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/passengers";

DataFrame[]

In [1]:
%sql
CREATE EXTERNAL VOLUME IF NOT EXISTS dev_flight_analytics.bronze.operational_data
COMMENT "Volume to hold the dimension data related to airplanes"
LOCATION "s3://ragesh-databricks-s3-inputs/flight_analytics/dev/bronze/operational_data/"

DataFrame[]